src/main/kotlin/team/gsm/flooding/domain/auth/dto/request/SignUpRequest.kt
src/main/kotlin/team/gsm/flooding/domain/auth/usecase/SignUpUsecase.kt
src/main/kotlin/team/gsm/flooding/domain/user/controller/UserController.kt
src/main/kotlin/team/gsm/flooding/domain/user/dto/response/FetchUserInfoResponse.kt
src/main/kotlin/team/gsm/flooding/domain/user/dto/response/StudentInfoResponse.kt
src/main/kotlin/team/gsm/flooding/domain/user/entity/Gender.kt
src/main/kotlin/team/gsm/flooding/domain/user/entity/Role.kt
src/main/kotlin/team/gsm/flooding/domain/user/entity/StudentInfo.kt
src/main/kotlin/team/gsm/flooding/domain/user/entity/User.kt
src/main/kotlin/team/gsm/flooding/domain/user/usecase/FetchUserUsecase.kt
src/main/kotlin/team/gsm/flooding/global/exception/ExceptionEnum.kt

유저 엔티티의 정보와 회원가입 로직 등을 수정하였습니다.
#null

🔁 유저 정보 수정

---

.github/workflows/gradle-ci.yml

 Gradle CI 추가

---

build.gradle.kts
src/main/kotlin/team/gsm/flooding/global/serverless/StreamLambdaHandler.kt

➕ 람다 핸들러 및 의존성 추가

---

src/main/kotlin/team/gsm/flooding/domain/health/HealthController.kt
src/main/kotlin/team/gsm/flooding/global/config/SecurityConfig.kt

🔀 서버 상태 API

---

src/main/kotlin/team/gsm/flooding/domain/attendance/controller/AttendanceController.kt
src/main/kotlin/team/gsm/flooding/domain/attendance/usecase/CancelHomebaseTableUsecase.kt
src/main/kotlin/team/gsm/flooding/global/config/SecurityConfig.kt
src/main/kotlin/team/gsm/flooding/global/exception/ExceptionEnum.kt

홈베이스 예약 취소 기능

---

src/main/kotlin/team/gsm/flooding/domain/user/controller/UserController.kt
src/main/kotlin/team/gsm/flooding/domain/user/dto/response/FetchUserInfoResponse.kt
src/main/kotlin/team/gsm/flooding/domain/user/repository/UserRepository.kt
src/main/kotlin/team/gsm/flooding/domain/user/usecase/FetchUserUsecase.kt
src/main/kotlin/team/gsm/flooding/domain/user/usecase/SearchUserUsecase.kt
src/main/kotlin/team/gsm/flooding/global/config/SecurityConfig.kt
src/main/kotlin/team/gsm/flooding/global/util/StudentUtil.kt

유저 검색 기능을 추가하였습니다.
#{ISSUE_ID}

🔀 유저 검색 기능 추가

---

src/main/kotlin/team/gsm/flooding/global/config/SecurityConfig.kt
src/main/kotlin/team/gsm/flooding/global/exception/dto/HttpExceptionResponse.kt
src/main/kotlin/team/gsm/flooding/global/security/filter/ExceptionFilter.kt

필터에서 발생하는 토큰 만료 등의 예외 처리를 반환하도록 설정합니다.
#10 

🔀 예외 필터 추가

---

src/main/kotlin/team/gsm/flooding/domain/attendance/entity/Attendance.kt
src/main/kotlin/team/gsm/flooding/domain/classroom/entity/Classroom.kt
src/main/kotlin/team/gsm/flooding/domain/club/entity/Club.kt
src/main/kotlin/team/gsm/flooding/domain/homebase/entity/HomebaseGroup.kt
src/main/kotlin/team/gsm/flooding/domain/user/entity/StudentInfo.kt
src/main/kotlin/team/gsm/flooding/domain/user/entity/User.kt

DDL에서 부족하거나 빠진 부분을 수정합니다.
#33 

데이터베이스 DDL 보완

---

src/main/kotlin/team/gsm/flooding/domain/club/controller/ClubController.kt
src/main/kotlin/team/gsm/flooding/domain/club/dto/response/ClubFilterResponse.kt
src/main/kotlin/team/gsm/flooding/domain/club/dto/response/FindClubFilterResponse.kt
src/main/kotlin/team/gsm/flooding/domain/club/repository/ClubRepository.kt
src/main/kotlin/team/gsm/flooding/domain/club/usecase/FindClubFilterUsecase.kt
src/main/kotlin/team/gsm/flooding/global/config/SecurityConfig.kt

동아리 필터 조회 API

---

src/main/kotlin/team/gsm/flooding/domain/club/controller/ClubController.kt
src/main/kotlin/team/gsm/flooding/domain/club/usecase/RemoveClubMemberUsecase.kt
src/main/kotlin/team/gsm/flooding/domain/clubMember/repository/ClubMemberRepository.kt
src/main/kotlin/team/gsm/flooding/global/config/SecurityConfig.kt
src/main/kotlin/team/gsm/flooding/global/exception/ExceptionEnum.kt

✨ 구성원 추방하기 기능

---

src/main/kotlin/team/gsm/flooding/domain/classroom/entity/BuildingType.kt
src/main/kotlin/team/gsm/flooding/domain/classroom/entity/Classroom.kt
src/main/kotlin/team/gsm/flooding/domain/club/entity/Club.kt
src/main/kotlin/team/gsm/flooding/domain/user/entity/User.kt

교실에 건물 유형 추가하기

---

Dockerfile

"나는 네가 알던 Docker가 아니다" 강력한 자동화로 돌아온 '살아있는 Auto' 출현... 절대 이 Dockerfile과 마주하지 마십시오

---

README.md
src/main/kotlin/team/gsm/flooding/domain/auth/controller/AuthController.kt
src/main/kotlin/team/gsm/flooding/domain/auth/dto/request/ReissueEmailCodeRequest.kt
src/main/kotlin/team/gsm/flooding/domain/auth/usecase/ReissueEmailCodeUsecase.kt
src/main/kotlin/team/gsm/flooding/domain/auth/usecase/SignOutUsecase.kt
src/main/kotlin/team/gsm/flooding/domain/club/controller/ClubController.kt
src/main/kotlin/team/gsm/flooding/domain/club/dto/response/FetchClubFilterResponse.kt
src/main/kotlin/team/gsm/flooding/domain/club/usecase/FetchClubFilterUsecase.kt
src/main/kotlin/team/gsm/flooding/domain/homebase/controller/HomebaseController.kt
src/main/kotlin/team/gsm/flooding/domain/homebase/dto/request/FetchReservedHomebaseTableRequest.kt
src/main/kotlin/team/gsm/flooding/domain/homebase/dto/response/FetchMyReservedHomebaseResponse.kt
src/main/kotlin/team/gsm/flooding/domain/homebase/dto/response/FetchReservedHomebaseResponse.kt
src/main/kotlin/team/gsm/flooding/domain/homebase/usecase/FetchMyReservedHomebaseUsecase.kt
src/main/kotlin/team/gsm/flooding/domain/homebase/usecase/FetchReservedHomebaseTableUsecase.kt
src/main/kotlin/team/gsm/flooding/domain/user/controller/UserController.kt
src/main/kotlin/team/gsm/flooding/domain/user/usecase/FetchFilteredUserUsecase.kt

도메인 용어 컨벤션

---

src/main/kotlin/team/gsm/flooding/domain/club/controller/ClubController.kt
src/main/kotlin/team/gsm/flooding/domain/club/dto/request/ApplyClubRequest.kt
src/main/kotlin/team/gsm/flooding/domain/club/entity/Club.kt
src/main/kotlin/team/gsm/flooding/domain/club/usecase/ApplyClubUsecase.kt
src/main/kotlin/team/gsm/flooding/global/config/SecurityConfig.kt
src/main/kotlin/team/gsm/flooding/global/exception/ExceptionEnum.kt

✨ 동아리 지원하기 기능

---

src/main/kotlin/team/gsm/flooding/domain/club/controller/ClubController.kt
src/main/kotlin/team/gsm/flooding/domain/club/dto/request/UpdateClubRequest.kt
src/main/kotlin/team/gsm/flooding/domain/club/usecase/UpdateClubUsecase.kt
src/main/kotlin/team/gsm/flooding/global/config/SecurityConfig.kt

🔀 동아리 수정 API

---

src/main/kotlin/team/gsm/flooding/domain/club/controller/ClubController.kt
src/main/kotlin/team/gsm/flooding/domain/club/usecase/OpenClubUsecase.kt
src/main/kotlin/team/gsm/flooding/global/config/SecurityConfig.kt

✨ 동아리 신청 열기 기능

---

src/main/kotlin/kr/flooding/backend/domain/club/controller/ClubController.kt
src/main/kotlin/kr/flooding/backend/domain/club/usecase/RemoveClubUsecase.kt
src/main/kotlin/kr/flooding/backend/global/config/SecurityConfig.kt

동아리 삭제 api

---

src/main/kotlin/kr/flooding/backend/domain/club/controller/ClubController.kt
src/main/kotlin/kr/flooding/backend/domain/club/usecase/CloseClubUsecase.kt
src/main/kotlin/kr/flooding/backend/global/config/SecurityConfig.kt

동아리 신청 마감 API

---

src/main/kotlin/kr/flooding/backend/domain/club/controller/ClubController.kt
src/main/kotlin/kr/flooding/backend/domain/club/usecase/WithdrawClubUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/clubMember/repository/ClubMemberRepository.kt
src/main/kotlin/kr/flooding/backend/global/config/SecurityConfig.kt

동아리 탈퇴 API

---

src/main/kotlin/kr/flooding/backend/domain/club/controller/ClubController.kt
src/main/kotlin/kr/flooding/backend/domain/club/usecase/InviteClubMemberUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/clubMember/repository/ClubMemberRepository.kt
src/main/kotlin/kr/flooding/backend/global/config/SecurityConfig.kt

구성원 초대 API

---

src/main/kotlin/kr/flooding/backend/domain/club/controller/ClubController.kt
src/main/kotlin/kr/flooding/backend/domain/club/dto/response/ClubMemberResponse.kt
src/main/kotlin/kr/flooding/backend/domain/club/dto/response/FetchClubResponse.kt
src/main/kotlin/kr/flooding/backend/domain/club/usecase/FetchClubUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/clubMember/repository/ClubMemberRepository.kt
src/main/kotlin/kr/flooding/backend/global/config/SecurityConfig.kt

동아리 단일 조회 API

---

src/main/kotlin/kr/flooding/backend/domain/user/controller/UserController.kt
src/main/kotlin/kr/flooding/backend/domain/user/entity/User.kt
src/main/kotlin/kr/flooding/backend/domain/user/usecase/UpdateProfileImageUsecase.kt
src/main/kotlin/kr/flooding/backend/global/config/SecurityConfig.kt

✨ 프로필 이미지 수정 API

---

src/main/kotlin/kr/flooding/backend/domain/auth/controller/AuthController.kt
src/main/kotlin/kr/flooding/backend/domain/auth/dto/request/ResetPasswordRequest.kt
src/main/kotlin/kr/flooding/backend/domain/auth/entity/VerifyCode.kt
src/main/kotlin/kr/flooding/backend/domain/auth/usecase/ReissueEmailCodeUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/auth/usecase/RequestResetPasswordUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/auth/usecase/ResetPasswordUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/auth/usecase/SignUpUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/user/entity/User.kt
src/main/kotlin/kr/flooding/backend/global/config/RedisConfig.kt
src/main/kotlin/kr/flooding/backend/global/config/SecurityConfig.kt
src/main/kotlin/kr/flooding/backend/global/exception/ExceptionEnum.kt
src/main/kotlin/kr/flooding/backend/global/thirdparty/email/EmailAdapter.kt
src/main/kotlin/kr/flooding/backend/global/util/PasswordUtil.kt
src/main/resources/application-dev.yml
src/main/resources/application-prod.yml

비밀번호 찾기 API와 잡다한 변경사항입니다.
#70 

비밀번호 찾기 API 및 기타 변경사항

---

src/main/kotlin/kr/flooding/backend/domain/auth/usecase/ReissueEmailCodeUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/auth/usecase/ReissueTokenUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/auth/usecase/RequestResetPasswordUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/auth/usecase/ResetPasswordUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/auth/usecase/SignInUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/auth/usecase/SignOutUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/auth/usecase/SignUpUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/auth/usecase/VerifyEmailUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/club/usecase/ApplyClubUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/club/usecase/CloseClubUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/club/usecase/CreateClubUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/club/usecase/FetchClubUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/club/usecase/InviteClubMemberUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/club/usecase/OpenClubUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/club/usecase/RemoveClubMemberUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/club/usecase/RemoveClubUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/club/usecase/UpdateClubUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/club/usecase/WithdrawClubUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/homebase/usecase/CancelHomebaseTableUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/homebase/usecase/ReserveHomebaseTableUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/neis/usecase/FetchMealInfoUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/neis/usecase/FetchTimetableUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/user/usecase/WithdrawUsecase.kt
src/main/kotlin/kr/flooding/backend/global/exception/ExceptionEnum.kt
src/main/kotlin/kr/flooding/backend/global/exception/HttpException.kt
src/main/kotlin/kr/flooding/backend/global/exception/dto/HttpExceptionResponse.kt
src/main/kotlin/kr/flooding/backend/global/security/filter/ExceptionFilter.kt
src/main/kotlin/kr/flooding/backend/global/security/jwt/JwtProvider.kt
src/main/kotlin/kr/flooding/backend/global/thirdparty/email/EmailAdapter.kt
src/main/kotlin/kr/flooding/backend/global/util/UserUtil.kt

계층형 예외 처리 설계 & 사소한 수정

---

src/main/kotlin/kr/flooding/backend/global/thirdparty/email/configuration/MailSenderConfig.kt

JavaMailSender Bean

---

src/main/kotlin/kr/flooding/backend/domain/homebase/controller/HomebaseController.kt

홈베이스 조회 쿼리스트링으로 변경

---

src/main/resources/application-dev.yml
src/main/resources/application-prod.yml
src/main/resources/application.yml

설정 분리 및 비밀번호 변경 URL 수정

---

src/main/kotlin/kr/flooding/backend/domain/auth/dto/request/SignUpRequest.kt
src/main/kotlin/kr/flooding/backend/domain/auth/usecase/ReissueEmailCodeUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/auth/usecase/SignInUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/auth/usecase/SignUpUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/auth/usecase/VerifyEmailUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/user/dto/response/FetchUserInfoResponse.kt
src/main/kotlin/kr/flooding/backend/domain/user/entity/Gender.kt
src/main/kotlin/kr/flooding/backend/domain/user/entity/User.kt
src/main/kotlin/kr/flooding/backend/domain/user/enums/Gender.kt
src/main/kotlin/kr/flooding/backend/domain/user/enums/Role.kt
src/main/kotlin/kr/flooding/backend/domain/user/enums/UserState.kt
src/main/kotlin/kr/flooding/backend/global/database/converter/StringListConverter.kt
src/main/kotlin/kr/flooding/backend/global/exception/ExceptionEnum.kt
src/main/kotlin/kr/flooding/backend/global/exception/handler/ExceptionHandler.kt
src/main/kotlin/kr/flooding/backend/global/security/configuration/SecurityConfig.kt

회원가입 로직 수정

---

src/main/kotlin/kr/flooding/backend/domain/auth/controller/AuthController.kt
src/main/kotlin/kr/flooding/backend/domain/club/controller/ClubController.kt
src/main/kotlin/kr/flooding/backend/domain/file/controller/FileController.kt
src/main/kotlin/kr/flooding/backend/domain/homebase/controller/HomebaseController.kt
src/main/kotlin/kr/flooding/backend/domain/neis/controller/NeisController.kt
src/main/kotlin/kr/flooding/backend/domain/user/controller/UserController.kt
src/main/kotlin/kr/flooding/backend/global/swagger/configuration/SwaggerConfig.kt
src/main/resources/application-dev.yml
src/main/resources/application-prod.yml
src/main/resources/application.yml

Swagger 가독성 향상을 위해서 설정 값을 변경하였습니다.
#98 

Swagger 가독성 향상

---

.editorconfig
src/main/kotlin/kr/flooding/backend/domain/attendance/controller/AttendanceController.kt
src/main/kotlin/kr/flooding/backend/domain/attendance/usecase/AbsenceClubLeaderUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/attendance/usecase/AbsenceClubMyselfUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/attendance/usecase/AttendClubLeaderUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/attendance/usecase/AttendClubMyselfUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/club/controller/ClubController.kt
src/main/kotlin/kr/flooding/backend/domain/club/dto/request/AbsenceClubLeaderRequest.kt
src/main/kotlin/kr/flooding/backend/domain/club/dto/response/ClubMyselfResponse.kt
src/main/kotlin/kr/flooding/backend/domain/club/dto/response/FetchClubMyselfResponse.kt
src/main/kotlin/kr/flooding/backend/domain/club/usecase/ApplyClubUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/club/usecase/ConfirmClubInviteUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/club/usecase/CreateClubUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/club/usecase/FetchClubMyselfUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/club/usecase/FetchClubUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/club/usecase/InviteClubMemberUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/club/usecase/RemoveClubMemberUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/club/usecase/WithdrawClubUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/clubMember/repository/jdsl/ClubMemberJdslRepository.kt
src/main/kotlin/kr/flooding/backend/domain/clubMember/repository/jdsl/impl/ClubMemberJdslRepositoryImpl.kt
src/main/kotlin/kr/flooding/backend/domain/clubMember/repository/jpa/ClubMemberJpaRepository.kt
src/main/kotlin/kr/flooding/backend/domain/period/entity/Period.kt
src/main/kotlin/kr/flooding/backend/domain/period/repository/PeriodRepository.kt
src/main/kotlin/kr/flooding/backend/global/exception/ExceptionEnum.kt
src/main/kotlin/kr/flooding/backend/global/security/configuration/SecurityConfig.kt
src/main/resources/application.yml

해당 교시 내에서만 출석을 변경할 수 있도록 코드를 추가하였습니다.
#112 
#111 
#110 

동아리 출석 시간 제한

---

src/main/kotlin/kr/flooding/backend/domain/auth/usecase/ReissueTokenUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/auth/usecase/SignInUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/auth/usecase/SignOutUsecase.kt
src/main/kotlin/kr/flooding/backend/global/security/jwt/JwtProvider.kt
src/main/resources/application.yml

엑세스 토큰과 리프레시 토큰의 키를 분리하였습니다.
#97

엑세스, 리프레시 토큰 키 분리

---

src/main/kotlin/kr/flooding/backend/domain/attendance/controller/AttendanceController.kt

API 잘못된 반환값 변경

---

src/main/kotlin/kr/flooding/backend/global/swagger/configuration/SwaggerConfig.kt

Swagger 네이밍 전략 수정

---

build.gradle.kts
src/main/kotlin/kr/flooding/backend/domain/music/controller/MusicController.kt
src/main/kotlin/kr/flooding/backend/domain/music/dto/request/CreateMusicRequest.kt
src/main/kotlin/kr/flooding/backend/domain/music/entity/Music.kt
src/main/kotlin/kr/flooding/backend/domain/music/repository/jpa/MusicJpaRepository.kt
src/main/kotlin/kr/flooding/backend/domain/music/usecase/CreateMusicUsecase.kt
src/main/kotlin/kr/flooding/backend/global/exception/ExceptionEnum.kt
src/main/kotlin/kr/flooding/backend/global/security/configuration/SecurityConfig.kt
src/main/kotlin/kr/flooding/backend/global/thirdparty/youtube/YoutubeAdapter.kt
src/main/kotlin/kr/flooding/backend/global/thirdparty/youtube/configuration/YoutubeConfig.kt
src/main/kotlin/kr/flooding/backend/global/thirdparty/youtube/dto/response/YoutubeInfoResponse.kt
src/main/resources/application.yml

기상 음악 신청 API

---

src/main/kotlin/kr/flooding/backend/domain/attendance/controller/AttendanceController.kt
src/main/kotlin/kr/flooding/backend/domain/attendance/dto/request/AbsenceClubLeaderRequest.kt
src/main/kotlin/kr/flooding/backend/domain/attendance/dto/request/AbsenceClubMyselfRequest.kt
src/main/kotlin/kr/flooding/backend/domain/attendance/dto/request/AttendClubLeaderRequest.kt
src/main/kotlin/kr/flooding/backend/domain/attendance/dto/request/AttendClubMyselfRequest.kt
src/main/kotlin/kr/flooding/backend/domain/attendance/dto/response/FetchAttendanceResponse.kt
src/main/kotlin/kr/flooding/backend/domain/attendance/repository/jpa/AttendanceJpaRepository.kt
src/main/kotlin/kr/flooding/backend/domain/attendance/usecase/AbsenceClubLeaderUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/attendance/usecase/AbsenceClubMyselfUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/attendance/usecase/AttendClubLeaderUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/attendance/usecase/AttendClubMyselfUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/attendance/usecase/FetchAttendanceUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/homebase/usecase/CancelHomebaseTableUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/homebase/usecase/ReserveHomebaseTableUsecase.kt
src/main/kotlin/kr/flooding/backend/global/exception/ExceptionEnum.kt
src/main/kotlin/kr/flooding/backend/global/security/configuration/SecurityConfig.kt

특정 교시의 출석 상태를 조회하는 API를 개발합니다.
#128 

출석 상태 조회 API

---

src/main/kotlin/kr/flooding/backend/domain/auth/usecase/SignUpUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/role/entity/Role.kt
src/main/kotlin/kr/flooding/backend/domain/role/enums/RoleType.kt
src/main/kotlin/kr/flooding/backend/domain/role/repository/jpa/RoleJpaRepository.kt
src/main/kotlin/kr/flooding/backend/domain/user/repository/jdsl/UserJdslRepository.kt
src/main/kotlin/kr/flooding/backend/domain/user/repository/jdsl/impl/UserJdslRepositoryImpl.kt
src/main/kotlin/kr/flooding/backend/domain/user/usecase/SearchStudentUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/user/usecase/SearchTeacherUsecase.kt
src/main/kotlin/kr/flooding/backend/global/database/converter/StringListConverter.kt
src/main/kotlin/kr/flooding/backend/global/security/configuration/CorsConfig.kt
src/main/kotlin/kr/flooding/backend/global/security/configuration/SecurityConfig.kt
src/main/kotlin/kr/flooding/backend/global/util/RoleUtil.kt

CORS allowedOrigins 변경
#139 
#138 

CORS allowedOrigins 변경

---

src/main/kotlin/kr/flooding/backend/domain/classroom/controller/ClassroomController.kt
src/main/kotlin/kr/flooding/backend/domain/club/controller/ClubController.kt
src/main/kotlin/kr/flooding/backend/domain/clubApplicant/controller/ClubApplicantController.kt
src/main/kotlin/kr/flooding/backend/domain/file/controller/FileController.kt
src/main/kotlin/kr/flooding/backend/domain/homebase/controller/HomebaseController.kt
src/main/kotlin/kr/flooding/backend/domain/music/controller/MusicController.kt
src/main/kotlin/kr/flooding/backend/domain/neis/controller/NeisController.kt
src/main/kotlin/kr/flooding/backend/domain/user/controller/UserController.kt

Swagger 문서 업데이트

---

src/main/kotlin/kr/flooding/backend/domain/club/controller/ClubController.kt
src/main/kotlin/kr/flooding/backend/domain/club/dto/response/FetchClubResponse.kt
src/main/kotlin/kr/flooding/backend/domain/club/entity/Club.kt
src/main/kotlin/kr/flooding/backend/domain/club/model/ClubClassroomModel.kt
src/main/kotlin/kr/flooding/backend/domain/club/repository/ClubRepository.kt
src/main/kotlin/kr/flooding/backend/domain/club/usecase/CreateClubUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/club/usecase/FetchClubFilterUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/club/usecase/FetchClubUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/clubMember/repository/jpa/ClubMemberJpaRepository.kt

- 동아리 조회 API를 수정했습니다.
- 동아리 테이블에 선생님을 추가했습니다.
#156 

동아리 조회 API 수정

---

src/main/kotlin/kr/flooding/backend/domain/club/dto/request/UpdateClubRequest.kt
src/main/kotlin/kr/flooding/backend/domain/club/dto/response/ClubFilterResponse.kt
src/main/kotlin/kr/flooding/backend/domain/club/repository/ClubRepository.kt
src/main/kotlin/kr/flooding/backend/domain/club/usecase/FetchClubFilterUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/club/usecase/UpdateClubUsecase.kt

동아리 필터 조회 시 승인된 동아리만 반환

---

src/main/kotlin/kr/flooding/backend/global/swagger/configuration/OpenApiConfig.kt

:recycle: OpenAPI 설정 파일 추가

---

build.gradle.kts
src/main/kotlin/kr/flooding/backend/FloodingApplication.kt
src/main/kotlin/kr/flooding/backend/domain/music/controller/MusicController.kt
src/main/kotlin/kr/flooding/backend/domain/music/dto/response/UpdateMusicLikeResponse.kt
src/main/kotlin/kr/flooding/backend/domain/music/entity/Music.kt
src/main/kotlin/kr/flooding/backend/domain/music/usecase/UpdateMusicLikeUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/music/usecase/helper/UpdateMusicLikeRetryHelper.kt
src/main/kotlin/kr/flooding/backend/domain/musicLike/entity/MusicLike.kt
src/main/kotlin/kr/flooding/backend/domain/musicLike/repository/jpa/MusicLikeJpaRepository.kt
src/main/kotlin/kr/flooding/backend/global/exception/ExceptionEnum.kt
src/main/kotlin/kr/flooding/backend/global/security/configuration/SecurityConfig.kt

기상 음악 좋아요 API

---

src/main/kotlin/kr/flooding/backend/domain/user/repository/jdsl/UserJdslRepository.kt
src/main/kotlin/kr/flooding/backend/domain/user/repository/jdsl/impl/UserJdslRepositoryImpl.kt
src/main/kotlin/kr/flooding/backend/domain/user/usecase/SearchStudentUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/user/usecase/SearchTeacherUsecase.kt

미인증 상태의 유저거나 빈 문자열이 들어오는 경우 미포함
#162 

유저 검색 API 수정

---

src/main/kotlin/kr/flooding/backend/global/database/configuration/RedisConfig.kt

- ConnectionFactory에 설정 추가
#{ISSUE_ID}

Redis 설정 변경

---

src/main/kotlin/kr/flooding/backend/domain/classroom/dto/response/ClassroomResponse.kt
src/main/kotlin/kr/flooding/backend/domain/classroom/dto/response/ClassroomTeacherResponse.kt
src/main/kotlin/kr/flooding/backend/domain/classroom/persistence/entity/Classroom.kt
src/main/kotlin/kr/flooding/backend/domain/classroom/persistence/repository/jdsl/impl/ClassroomJdslRepositoryImpl.kt
src/main/kotlin/kr/flooding/backend/domain/homebase/controller/HomebaseController.kt
src/main/kotlin/kr/flooding/backend/domain/homebase/dto/common/response/FetchMyReservedHomebaseResponse.kt
src/main/kotlin/kr/flooding/backend/domain/homebase/dto/common/response/FetchReservedHomebaseResponse.kt
src/main/kotlin/kr/flooding/backend/domain/homebase/dto/common/response/HomebaseParticipantResponse.kt
src/main/kotlin/kr/flooding/backend/domain/homebase/dto/common/response/HomebaseTableResponse.kt
src/main/kotlin/kr/flooding/backend/domain/homebase/dto/web/request/FetchReservedHomebaseTableRequest.kt
src/main/kotlin/kr/flooding/backend/domain/homebase/dto/web/request/ReserveHomebaseTableRequest.kt
src/main/kotlin/kr/flooding/backend/domain/homebase/dto/web/response/FetchMyReservedHomebaseListResponse.kt
src/main/kotlin/kr/flooding/backend/domain/homebase/dto/web/response/FetchReservedHomebaseListResponse.kt
src/main/kotlin/kr/flooding/backend/domain/homebase/persistence/entity/HomebaseGroup.kt
src/main/kotlin/kr/flooding/backend/domain/homebase/usecase/FetchMyReservedHomebaseUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/homebase/usecase/FetchReservedHomebaseTableUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/homebase/usecase/ReserveHomebaseTableUsecase.kt

홈베이스 예약 시 사유를 입력하도록 변경하였습니다.
#176 

홈베이스 예약 시 사유 필수

---

src/main/kotlin/kr/flooding/backend/domain/club/dto/request/CreateClubRequest.kt
src/main/kotlin/kr/flooding/backend/domain/club/dto/response/ClubFilterResponse.kt
src/main/kotlin/kr/flooding/backend/domain/club/dto/response/ClubMyselfResponse.kt
src/main/kotlin/kr/flooding/backend/domain/club/dto/response/FetchClubResponse.kt
src/main/kotlin/kr/flooding/backend/domain/club/persistence/entity/Club.kt
src/main/kotlin/kr/flooding/backend/domain/club/usecase/CreateClubUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/club/usecase/FetchClubFilterUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/club/usecase/FetchClubMyselfUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/club/usecase/FetchClubUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/club/usecase/UpdateClubUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/file/usecase/UploadImageUsecase.kt
src/main/kotlin/kr/flooding/backend/global/thirdparty/s3/S3ClientConfig.kt
src/main/kotlin/kr/flooding/backend/global/util/S3Util.kt
src/main/resources/application.yml

S3 마이그레이션으로 인한, 이미지 업로드 로직 수정
#178 

S3 마이그레이션으로 인한, 이미지 업로드 로직 수정

---

src/main/kotlin/kr/flooding/backend/domain/user/controller/UserController.kt
src/main/kotlin/kr/flooding/backend/domain/user/dto/request/UpdateProfileRequest.kt
src/main/kotlin/kr/flooding/backend/domain/user/persistence/entity/User.kt
src/main/kotlin/kr/flooding/backend/domain/user/usecase/UpdateProfileImageUsecase.kt

프로필 변경 로직 수정

---

build.gradle.kts
src/main/kotlin/kr/flooding/backend/domain/file/usecase/UploadImageUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/user/dto/request/UpdateProfileRequest.kt
src/main/kotlin/kr/flooding/backend/global/exception/ExceptionEnum.kt
src/main/kotlin/kr/flooding/backend/global/util/ImageUtil.kt

이미지 업로드 시 webp 변환

---

src/main/kotlin/kr/flooding/backend/domain/massage/controller/MassageController.kt
src/main/kotlin/kr/flooding/backend/domain/massage/persistence/entity/Massage.kt
src/main/kotlin/kr/flooding/backend/domain/massage/persistence/entity/MassageReservation.kt
src/main/kotlin/kr/flooding/backend/domain/massage/persistence/repository/jpa/MassageJpaRepository.kt
src/main/kotlin/kr/flooding/backend/domain/massage/persistence/repository/jpa/MassageReservationJpaRepository.kt
src/main/kotlin/kr/flooding/backend/domain/massage/scheduler/MassageScheduler.kt
src/main/kotlin/kr/flooding/backend/domain/massage/usecase/ReserveMassageUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/selfStudy/scheduler/MassageScheduler.kt
src/main/kotlin/kr/flooding/backend/global/exception/ExceptionEnum.kt
src/main/kotlin/kr/flooding/backend/global/security/configuration/SecurityConfig.kt

안마의자 신청 API

---

buildspec.yml

add buildspec.yml

---

scripts/before_install.sh

add update scripts

---

appspec.yml
scripts/start.sh

update appspec, start

---

src/main/kotlin/kr/flooding/backend/domain/club/dto/response/ClubStudentResponse.kt
src/main/kotlin/kr/flooding/backend/domain/club/dto/response/ClubTeacherResponse.kt
src/main/kotlin/kr/flooding/backend/domain/club/dto/response/FetchClubResponse.kt
src/main/kotlin/kr/flooding/backend/domain/club/usecase/FetchClubUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/clubApplicant/persistence/repository/jpa/ClubApplicantJpaRepository.kt

동아리 구성원 프로필 이미지 반환

---

src/main/kotlin/kr/flooding/backend/domain/neis/usecase/FetchMealInfoUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/neis/usecase/FetchTimetableUsecase.kt

급식, 시간표 API 수정

---

src/main/kotlin/kr/flooding/backend/domain/homebase/dto/common/response/FetchMyReservedHomebaseResponse.kt
src/main/kotlin/kr/flooding/backend/domain/homebase/dto/common/response/FetchReservedHomebaseResponse.kt
src/main/kotlin/kr/flooding/backend/domain/homebase/persistence/repository/jdsl/impl/HomebaseGroupJdslRepositoryImpl.kt

홈베이스 조회 API 쿼리 변경

---

src/main/kotlin/kr/flooding/backend/domain/homebase/dto/common/response/FetchMyReservedHomebaseResponse.kt
src/main/kotlin/kr/flooding/backend/domain/homebase/dto/common/response/FetchReservedHomebaseResponse.kt

홈베이스 조회 시, participants에 신청자를 포함
#212 

홈베이스 조회 시, participants에 신청자를 포함

---

src/main/kotlin/kr/flooding/backend/global/swagger/configuration/OpenApiConfig.kt

OpenAPI 서버 목록 추가

---

src/main/kotlin/kr/flooding/backend/domain/massage/controller/MassageAdminController.kt
src/main/kotlin/kr/flooding/backend/domain/massage/dto/ChangeMassageLimitRequest.kt
src/main/kotlin/kr/flooding/backend/domain/massage/usecase/ChangeMassageLimitUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/selfStudy/controller/SelfStudyAdminController.kt
src/main/kotlin/kr/flooding/backend/global/security/configuration/SecurityConfig.kt

안마의자 최대 인원 변경 API

---

src/main/kotlin/kr/flooding/backend/domain/attendance/controller/AttendanceController.kt
src/main/kotlin/kr/flooding/backend/domain/attendance/dto/common/response/FetchClubAttendanceResponse.kt
src/main/kotlin/kr/flooding/backend/domain/attendance/dto/web/request/AbsenceClubLeaderRequest.kt
src/main/kotlin/kr/flooding/backend/domain/attendance/dto/web/request/AbsenceClubMyselfRequest.kt
src/main/kotlin/kr/flooding/backend/domain/attendance/dto/web/request/AttendClubLeaderRequest.kt
src/main/kotlin/kr/flooding/backend/domain/attendance/dto/web/request/AttendClubMyselfRequest.kt
src/main/kotlin/kr/flooding/backend/domain/attendance/dto/web/request/FetchClubAttendanceRequest.kt
src/main/kotlin/kr/flooding/backend/domain/attendance/dto/web/response/FetchAttendanceResponse.kt
src/main/kotlin/kr/flooding/backend/domain/attendance/dto/web/response/FetchClubAttendanceListResponse.kt
src/main/kotlin/kr/flooding/backend/domain/attendance/enums/AttendanceStatus.kt
src/main/kotlin/kr/flooding/backend/domain/attendance/persistence/repository/jdsl/AttendanceJdslRepository.kt
src/main/kotlin/kr/flooding/backend/domain/attendance/persistence/repository/jdsl/impl/AttendanceJdslRepositoryImpl.kt
src/main/kotlin/kr/flooding/backend/domain/attendance/persistence/repository/jpa/AttendanceJpaRepository.kt
src/main/kotlin/kr/flooding/backend/domain/attendance/usecase/AbsenceClubLeaderUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/attendance/usecase/AbsenceClubMyselfUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/attendance/usecase/AttendClubLeaderUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/attendance/usecase/AttendClubMyselfUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/attendance/usecase/FetchClubAttendanceUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/attendance/usecase/FetchMyselfAttendanceUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/club/usecase/CreateClubUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/club/usecase/FetchClubUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/clubApplicant/usecase/ApplyClubUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/clubMember/persistence/repository/jdsl/ClubMemberJdslRepository.kt
src/main/kotlin/kr/flooding/backend/domain/clubMember/persistence/repository/jdsl/impl/ClubMemberJdslRepositoryImpl.kt
src/main/kotlin/kr/flooding/backend/domain/clubMember/persistence/repository/jpa/ClubMemberJpaRepository.kt
src/main/kotlin/kr/flooding/backend/domain/homebase/usecase/CancelHomebaseTableUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/homebase/usecase/ReserveHomebaseTableUsecase.kt
src/main/kotlin/kr/flooding/backend/global/security/configuration/SecurityConfig.kt

출석 전체 조회 API

---

src/main/kotlin/kr/flooding/backend/domain/attendance/usecase/FetchClubAttendanceUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/club/usecase/FetchClubFilterUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/club/usecase/FetchClubMyselfUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/club/usecase/FetchClubUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/file/usecase/UploadImageUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/massage/controller/MassageAdminController.kt
src/main/kotlin/kr/flooding/backend/domain/massage/controller/MassageController.kt
src/main/kotlin/kr/flooding/backend/domain/massage/dto/request/ChangeMassageLimitRequest.kt
src/main/kotlin/kr/flooding/backend/domain/massage/dto/response/FetchMassageResponse.kt
src/main/kotlin/kr/flooding/backend/domain/massage/enums/MassageStatus.kt
src/main/kotlin/kr/flooding/backend/domain/massage/persistence/entity/MassageRoom.kt
src/main/kotlin/kr/flooding/backend/domain/massage/persistence/repository/jpa/MassageRoomJpaRepository.kt
src/main/kotlin/kr/flooding/backend/domain/massage/scheduler/MassageScheduler.kt
src/main/kotlin/kr/flooding/backend/domain/massage/usecase/CancelMassageUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/massage/usecase/ChangeMassageLimitUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/massage/usecase/FetchMassageUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/massage/usecase/ReserveMassageUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/user/dto/web/response/FetchUserInfoResponse.kt
src/main/kotlin/kr/flooding/backend/domain/user/usecase/admin/FetchPendingUserListUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/user/usecase/common/FetchUserUsecase.kt
src/main/kotlin/kr/flooding/backend/global/redis/config/RedisConfig.kt
src/main/kotlin/kr/flooding/backend/global/security/configuration/SecurityConfig.kt
src/main/kotlin/kr/flooding/backend/global/thirdparty/s3/adapter/S3Adapter.kt
src/main/kotlin/kr/flooding/backend/global/thirdparty/s3/config/S3Config.kt
src/main/kotlin/kr/flooding/backend/global/util/FileUtil.kt

안마의자 조회 API

---

src/main/kotlin/kr/flooding/backend/domain/massage/controller/MassageController.kt
src/main/kotlin/kr/flooding/backend/domain/massage/dto/response/FetchMassageRankListResponse.kt
src/main/kotlin/kr/flooding/backend/domain/massage/dto/response/FetchMassageRankResponse.kt
src/main/kotlin/kr/flooding/backend/domain/massage/dto/response/FetchMassageResponse.kt
src/main/kotlin/kr/flooding/backend/domain/massage/enums/MassageStatus.kt
src/main/kotlin/kr/flooding/backend/domain/massage/persistence/repository/jdsl/MassageReservationJdslRepository.kt
src/main/kotlin/kr/flooding/backend/domain/massage/persistence/repository/jdsl/impl/MassageReservationJdslRepositoryImpl.kt
src/main/kotlin/kr/flooding/backend/domain/massage/persistence/repository/jpa/MassageReservationJpaRepository.kt
src/main/kotlin/kr/flooding/backend/domain/massage/usecase/FetchMassageRankUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/massage/usecase/FetchMassageUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/user/persistence/entity/StudentInfo.kt
src/main/kotlin/kr/flooding/backend/global/security/configuration/SecurityConfig.kt

안마의자 순위 API 

---

src/main/kotlin/kr/flooding/backend/domain/attendance/dto/common/response/FetchClubAttendanceResponse.kt
src/main/kotlin/kr/flooding/backend/domain/attendance/usecase/FetchClubAttendanceUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/club/dto/common/response/ClubFilterResponse.kt
src/main/kotlin/kr/flooding/backend/domain/club/dto/common/response/ClubMyselfResponse.kt
src/main/kotlin/kr/flooding/backend/domain/club/dto/common/response/ClubStudentResponse.kt
src/main/kotlin/kr/flooding/backend/domain/club/dto/common/response/ClubTeacherResponse.kt
src/main/kotlin/kr/flooding/backend/domain/club/dto/web/response/FetchClubResponse.kt
src/main/kotlin/kr/flooding/backend/domain/club/usecase/FetchClubFilterUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/club/usecase/FetchClubMyselfUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/club/usecase/FetchClubUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/file/dto/common/response/UploadImageResponse.kt
src/main/kotlin/kr/flooding/backend/domain/file/dto/web/response/UploadImageListResponse.kt
src/main/kotlin/kr/flooding/backend/domain/file/shared/PresignedUrlModel.kt
src/main/kotlin/kr/flooding/backend/domain/file/usecase/UploadImageUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/massage/dto/response/FetchMassageRankResponse.kt
src/main/kotlin/kr/flooding/backend/domain/massage/usecase/FetchMassageRankUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/selfStudy/dto/response/FetchSelfStudyResponse.kt
src/main/kotlin/kr/flooding/backend/domain/selfStudy/usecase/FetchSelfStudyStudentUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/user/dto/common/response/PendingUserResponse.kt
src/main/kotlin/kr/flooding/backend/domain/user/dto/web/response/FetchUserMyselfResponse.kt
src/main/kotlin/kr/flooding/backend/domain/user/usecase/admin/FetchPendingUserListUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/user/usecase/common/FetchUserMyselfUsecase.kt
src/main/kotlin/kr/flooding/backend/global/thirdparty/s3/adapter/S3Adapter.kt

Presigned URL 공통 모델로 변경

---

src/main/kotlin/kr/flooding/backend/domain/attendance/dto/common/response/FetchClubAttendanceResponse.kt
src/main/kotlin/kr/flooding/backend/domain/attendance/usecase/FetchClubAttendanceUsecase.kt

출석 조회 API id 추가 반환

---

src/main/kotlin/kr/flooding/backend/domain/attendance/controller/AttendanceController.kt
src/main/kotlin/kr/flooding/backend/domain/attendance/dto/web/request/AbsenceClubManagerRequest.kt
src/main/kotlin/kr/flooding/backend/domain/attendance/dto/web/request/AttendClubManagerRequest.kt
src/main/kotlin/kr/flooding/backend/domain/attendance/usecase/AbsenceClubManagerUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/attendance/usecase/AttendClubManagerUsecase.kt
src/main/kotlin/kr/flooding/backend/global/exception/ExceptionEnum.kt
src/main/kotlin/kr/flooding/backend/global/security/configuration/SecurityConfig.kt

> 동아리 담당 선생님도 출석 상태를 변경 가능하도록 변경했습니다.
#228 

동아리 담당 선생님 출석 상태 변경

---

src/main/kotlin/kr/flooding/backend/domain/user/persistence/entity/User.kt

@Enumerated 적용

---

src/main/kotlin/kr/flooding/backend/domain/attendance/usecase/FetchClubAttendanceUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/club/dto/web/response/FetchClubResponse.kt
src/main/kotlin/kr/flooding/backend/domain/club/persistence/entity/Club.kt
src/main/kotlin/kr/flooding/backend/domain/club/usecase/FetchClubUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/clubMember/persistence/repository/jdsl/ClubMemberJdslRepository.kt
src/main/kotlin/kr/flooding/backend/domain/clubMember/persistence/repository/jdsl/impl/ClubMemberJdslRepositoryImpl.kt
src/main/kotlin/kr/flooding/backend/domain/massage/usecase/FetchMassageStatusUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/selfStudy/usecase/FetchSelfStudyStatusUsecase.kt

- 동아리 신청자, 교실 정보를 nullable 타입으로 수정
#277 

동아리 엔티티 필드 nullable 타입 수정

---

src/main/kotlin/kr/flooding/backend/domain/massage/persistence/entity/MassageRoom.kt
src/main/kotlin/kr/flooding/backend/domain/massage/persistence/repository/jpa/MassageReservationJpaRepository.kt
src/main/kotlin/kr/flooding/backend/domain/massage/scheduler/MassageScheduler.kt
src/main/kotlin/kr/flooding/backend/domain/massage/usecase/CancelMassageUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/massage/usecase/FetchMassageStatusUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/massage/usecase/ReserveMassageUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/selfStudy/persistence/entity/SelfStudyRoom.kt
src/main/kotlin/kr/flooding/backend/domain/selfStudy/persistence/repository/jdsl/SelfStudyReservationJdslRepository.kt
src/main/kotlin/kr/flooding/backend/domain/selfStudy/persistence/repository/jdsl/impl/SelfStudyReservationJdslRepositoryImpl.kt
src/main/kotlin/kr/flooding/backend/domain/selfStudy/persistence/repository/jpa/SelfStudyReservationJpaRepository.kt
src/main/kotlin/kr/flooding/backend/domain/selfStudy/scheduler/SelfStudyScheduler.kt
src/main/kotlin/kr/flooding/backend/domain/selfStudy/usecase/FetchSelfStudyStatusUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/selfStudy/usecase/FetchSelfStudyStudentUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/selfStudy/usecase/helper/CancelSelfStudyRetryHelper.kt
src/main/kotlin/kr/flooding/backend/domain/selfStudy/usecase/helper/ReserveSelfStudyRetryHelper.kt

안마의자와 자습 테이블 구조 변경

---

src/main/kotlin/kr/flooding/backend/domain/music/usecase/student/DeleteOldMusicUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/selfStudy/persistence/repository/jpa/SelfStudyReservationJpaRepository.kt
src/main/kotlin/kr/flooding/backend/domain/selfStudy/scheduler/SelfStudyBanScheduler.kt
src/main/kotlin/kr/flooding/backend/domain/selfStudy/usecase/BanForSelfStudyAbsenceUsecase.kt

- 12시에 자습이 끝난 시점에서 출석이 되지 않은 유저 정지
#286 

12시에 자습이 끝난 시점에서 출석이 되지 않은 유저 정지

---

src/main/kotlin/kr/flooding/backend/domain/music/persistence/entity/Music.kt
src/main/kotlin/kr/flooding/backend/domain/music/persistence/repository/jdsl/impl/MusicJdslRepositoryImpl.kt
src/main/kotlin/kr/flooding/backend/domain/music/persistence/repository/jpa/MusicJpaRepository.kt
src/main/kotlin/kr/flooding/backend/domain/music/usecase/student/CreateMusicUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/music/usecase/student/DeleteOldMusicUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/music/usecase/student/RemoveMusicMyselfUsecase.kt

- 음악 신청 동시성 문제 해결을 위해 Music 엔티티에 유니크 제약을 추가했습니다.
#289 

음악 신청 동시성 문제 해결

---

src/main/kotlin/kr/flooding/backend/domain/attendance/persistence/entity/Attendance.kt
src/main/kotlin/kr/flooding/backend/domain/classroom/persistence/entity/Classroom.kt
src/main/kotlin/kr/flooding/backend/domain/club/persistence/entity/Club.kt
src/main/kotlin/kr/flooding/backend/domain/club/usecase/ConfirmClubInviteUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/club/usecase/CreateClubUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/clubApplicant/persistence/entity/ClubApplicant.kt
src/main/kotlin/kr/flooding/backend/domain/clubApplicant/usecase/ApplyClubUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/clubApplicant/usecase/ApproveClubApplicantUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/clubMember/persistence/entity/ClubMember.kt
src/main/kotlin/kr/flooding/backend/domain/homebase/persistence/entity/HomebaseGroup.kt
src/main/kotlin/kr/flooding/backend/domain/homebase/persistence/repository/jpa/HomebaseGroupRepository.kt
src/main/kotlin/kr/flooding/backend/domain/homebaseParticipants/persistence/entity/HomebaseParticipant.kt
src/main/kotlin/kr/flooding/backend/domain/homebaseTable/persistence/entity/HomebaseTable.kt
src/main/kotlin/kr/flooding/backend/domain/period/persistence/entity/Period.kt
src/main/kotlin/kr/flooding/backend/domain/role/persistence/entity/Role.kt
src/main/kotlin/kr/flooding/backend/domain/selfStudy/persistence/entity/SelfStudyBan.kt
src/main/kotlin/kr/flooding/backend/domain/selfStudy/persistence/entity/SelfStudyReservation.kt
src/main/kotlin/kr/flooding/backend/global/exception/handler/ExceptionHandler.kt

- 복합 키를 사용하는 엔티티에 유니크 제약조건 추가
#293 

복합 키 사용 엔티티 유니크 제약조건 추가

---

src/main/kotlin/kr/flooding/backend/domain/attendance/persistence/entity/Attendance.kt
src/main/kotlin/kr/flooding/backend/domain/club/usecase/RemoveClubMemberUsecase.kt

- 동아리 부장 자기 자신 추방 금지
- 출석 엔티티 Club 컬럼 OnDelete 설정
#300 

동아리 부장 자기 자신 추방 금지

---

src/main/kotlin/kr/flooding/backend/domain/selfStudy/controller/SelfStudyAdminController.kt
src/main/kotlin/kr/flooding/backend/domain/selfStudy/persistence/repository/jpa/SelfStudyBanJpaRepository.kt
src/main/kotlin/kr/flooding/backend/domain/selfStudy/usecase/CancelSelfStudyBanUsecase.kt
src/main/kotlin/kr/flooding/backend/global/exception/ExceptionEnum.kt
src/main/kotlin/kr/flooding/backend/global/security/configuration/SecurityConfig.kt

자습 정지 취소 API

---

src/main/kotlin/kr/flooding/backend/domain/homebase/persistence/repository/jdsl/HomebaseGroupJdslRepository.kt
src/main/kotlin/kr/flooding/backend/domain/homebase/persistence/repository/jdsl/impl/HomebaseGroupJdslRepositoryImpl.kt
src/main/kotlin/kr/flooding/backend/domain/homebase/usecase/ReserveHomebaseTableUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/homebaseParticipants/persistence/jpa/HomebaseParticipantRepository.kt

홈베이스 중복 신청 문제 해결

---

src/main/kotlin/kr/flooding/backend/domain/auth/usecase/SignInUsecase.kt
src/main/kotlin/kr/flooding/backend/domain/user/persistence/entity/StudentInfo.kt
src/main/kotlin/kr/flooding/backend/global/exception/ExceptionEnum.kt

- 당해년도 졸업생의 1월을 제외한 졸업생 로그인 금지
#260 

졸업생 로그인 금지

---

src/main/kotlin/kr/flooding/backend/domain/homebase/scheduler/HomebaseScheduler.kt

홈베이스 예약 삭제 스케줄러

---

src/main/kotlin/kr/flooding/backend/domain/auth/dto/request/SignUpStudentRequest.kt

- 회원가입 이름 입력 한글 2~7자 제한 정규식 추가
#292 

회원가입 이름 정규식
